# Generated by Django 5.2.2 on 2025-06-09 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('fa61e908-c267-46c9-9a7f-484de5e730f2'), editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
